import secrets
import datetime
import json
from fastapi import APIRouter, Depends, HTTPException, Response
from fastapi.responses import HTMLResponse, PlainTextResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from database import get_db
from models import User, Workspace, Finding as FindingORM, Order as OrderORM, AuditLog as AuditLogORM
from security import get_current_user, verify_workspace_access
from schemas.workspace_schemas import AuditRunResponse
from services.merchant_audit_service import run_merchant_workspace_audit

router = APIRouter(prefix="/api/workspaces/{workspace_id}", tags=["Merchant Audit"])


@router.post("/audit/run", response_model=AuditRunResponse)
async def trigger_audit_run(
    workspace_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Execute the deterministic audit engine on tenant-isolated merchant workspace data."""
    await verify_workspace_access(workspace_id, user, db, min_role="auditor")
    try:
        res = await run_merchant_workspace_audit(workspace_id, user.id, db)
        return AuditRunResponse(**res)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Audit execution error: {str(e)}")


@router.get("/reports/{format}")
async def export_workspace_report(
    workspace_id: str,
    format: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Export an evidence-based audit report for this private merchant workspace."""
    ws = await verify_workspace_access(workspace_id, user, db, min_role="viewer")
    
    if format not in ["html", "json", "markdown", "md"]:
        raise HTTPException(status_code=400, detail=f"Unsupported format '{format}'. Supported formats: html, json, markdown")
        
    findings = (await db.execute(
        select(FindingORM).where(FindingORM.workspace_id == workspace_id, FindingORM.is_healthy_control == False)
    )).scalars().all()
    
    healthy = (await db.execute(
        select(FindingORM).where(FindingORM.workspace_id == workspace_id, FindingORM.is_healthy_control == True)
    )).scalars().all()
    
    order_count = (await db.execute(
        select(OrderORM.id).where(OrderORM.workspace_id == workspace_id)
    )).scalars().all()
    
    now_iso = datetime.datetime.now(datetime.timezone.utc).isoformat()
    
    # Record AuditLog
    db.add(AuditLogORM(
        id=f"log_{secrets.token_hex(8)}",
        workspace_id=workspace_id,
        user_id=user.id,
        action="report_exported",
        details={"format": format, "findings_count": len(findings)},
        timestamp=now_iso
    ))
    await db.commit()
    
    if format == "json":
        export_payload = {
            "workspace_id": workspace_id,
            "workspace_name": ws.name,
            "exported_at": now_iso,
            "total_orders": len(order_count),
            "findings_count": len(findings),
            "healthy_controls_count": len(healthy),
            "findings": [
                {
                    "id": f.id,
                    "rule_id": f.rule_id,
                    "rule_name": f.rule_name,
                    "category": f.category,
                    "severity": f.severity,
                    "order_id": f.order_id,
                    "observed": f.observed,
                    "amount_minor": f.amount_minor,
                    "amount_currency": f.amount_currency,
                    "confidence": f.confidence,
                    "explanation": f.explanation,
                    "recommended_action": f.recommended_action,
                    "not_proven": f.not_proven,
                    "next_step": f.next_step,
                    "status": f.status
                }
                for f in findings
            ],
            "boundary_disclaimer": "CONFIDENTIAL AUDIT REPORT — Deterministic discrepancy analysis. Does not constitute proof of fraud or legal certification."
        }
        return Response(
            content=json.dumps(export_payload, indent=2),
            media_type="application/json",
            headers={"Content-Disposition": f"attachment; filename=ctl-audit-{workspace_id}.json"}
        )
        
    elif format in ["markdown", "md"]:
        md_lines = [
            f"# Audit Report — {ws.name}",
            "",
            "> **CONFIDENTIAL MERCHANT AUDIT REPORT**",
            "> Generated by Commerce Truth Lab (CTL Engine v1.0).",
            "> Discrepancies represent deterministic reconciliation gaps based strictly on provided records.",
            "> *Anti-Hype Notice: Does not prove fraud, causal ROAS, or guarantee recovered cash.*",
            "",
            "## Executive Summary",
            f"- **Workspace:** {ws.name} (`{workspace_id}`)",
            f"- **Generated At:** {now_iso}",
            f"- **Total Orders Audited:** {len(order_count)}",
            f"- **Reconciliation Exceptions (Findings):** {len(findings)}",
            f"- **Verified Healthy Controls:** {len(healthy)}",
            "",
            "## Identified Discrepancies",
            "| Rule | Severity | Order ID | Observation | Next Step |",
            "|---|---|---|---|---|"
        ]
        for f in findings:
            md_lines.append(f"| {f.rule_id}: {f.rule_name} | {f.severity.upper()} | {f.order_id or 'N/A'} | {f.observed} | {f.next_step} |")
            
        md_lines.extend([
            "",
            "## Methodological Guardrails",
            "1. **Zero False Claims:** Findings indicate data discrepancies between sources, not confirmed theft or recovered revenue.",
            "2. **Evidence Completeness:** Incomplete evidence states are flagged explicitly (CTL-009) rather than guessed.",
            "3. **Customer Privacy:** All customer identifiers in this audit were pseudonymized prior to ingestion.",
            "",
            "---",
            "*Commerce Truth Lab v1.0 — Syed Muslim Shah (Portfolio: https://syed-muslim-shah-portfolio.vercel.app/)*"
        ])
        return PlainTextResponse(
            content="\n".join(md_lines),
            media_type="text/markdown",
            headers={"Content-Disposition": f"attachment; filename=ctl-audit-{workspace_id}.md"}
        )
        
    else:  # html
        rows_html = "".join([
            f"<tr>"
            f"<td><strong>{f.rule_id}</strong><br><small>{f.rule_name}</small></td>"
            f"<td><span class='badge badge-{f.severity.lower()}'>{f.severity.upper()}</span></td>"
            f"<td><code>{f.order_id or 'N/A'}</code></td>"
            f"<td>{f.observed}</td>"
            f"<td>{f.next_step}</td>"
            f"</tr>"
            for f in findings
        ])
        
        html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Commerce Truth Lab — Audit Report: {ws.name}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.5; color: #1e293b; background: #f8fafc; padding: 32px; max-width: 1100px; margin: 0 auto; }}
        .header {{ border-bottom: 2px solid #e2e8f0; padding-bottom: 16px; margin-bottom: 24px; }}
        .banner {{ background: #eff6ff; border-left: 4px solid #3b82f6; padding: 12px 16px; border-radius: 4px; margin-bottom: 24px; font-size: 14px; color: #1e40af; }}
        .metrics {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 28px; }}
        .card {{ background: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }}
        .card h4 {{ margin: 0 0 8px 0; font-size: 13px; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; }}
        .card .num {{ font-size: 28px; font-weight: 700; color: #0f172a; }}
        table {{ width: 100%; border-collapse: collapse; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; margin-bottom: 32px; }}
        th {{ background: #f1f5f9; text-align: left; padding: 12px; font-size: 12px; text-transform: uppercase; color: #475569; letter-spacing: 0.05em; }}
        td {{ padding: 12px; border-top: 1px solid #e2e8f0; font-size: 13px; vertical-align: top; }}
        .badge {{ display: inline-block; padding: 3px 8px; border-radius: 4px; font-weight: 600; font-size: 11px; }}
        .badge-critical {{ background: #fee2e2; color: #991b1b; }}
        .badge-high {{ background: #ffedd5; color: #9a3412; }}
        .badge-medium {{ background: #fef9c3; color: #854d0e; }}
        .badge-low {{ background: #e0e7ff; color: #3730a3; }}
        code {{ background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-family: monospace; font-size: 12px; }}
        .footer {{ font-size: 12px; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 24px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Commerce Truth Lab — Audit Report</h1>
        <p style="color: #64748b; margin: 4px 0 0 0;">Workspace: <strong>{ws.name}</strong> ({workspace_id}) &bull; Generated: {now_iso}</p>
    </div>
    
    <div class="banner">
        <strong>Confidential Merchant Audit:</strong> Deterministic discrepancy detection based strictly on uploaded records. Customer identifiers are pseudonymized with salted cryptographic hashes. Discrepancies reflect reconciliation variance and missing signals, not verified fraud or recovered cash.
    </div>
    
    <div class="metrics">
        <div class="card">
            <h4>Audited Orders</h4>
            <div class="num">{len(order_count)}</div>
        </div>
        <div class="card">
            <h4>Exceptions Detected</h4>
            <div class="num" style="color: #dc2626;">{len(findings)}</div>
        </div>
        <div class="card">
            <h4>Healthy Controls</h4>
            <div class="num" style="color: #16a34a;">{len(healthy)}</div>
        </div>
    </div>
    
    <h2>Reconciliation Discrepancies ({len(findings)})</h2>
    <table>
        <thead>
            <tr>
                <th style="width: 20%;">Rule</th>
                <th style="width: 12%;">Severity</th>
                <th style="width: 15%;">Order ID</th>
                <th>Observation</th>
                <th style="width: 22%;">Recommended Next Step</th>
            </tr>
        </thead>
        <tbody>
            {rows_html if findings else "<tr><td colspan='5' style='text-align: center; color: #64748b; padding: 32px;'>No audit discrepancies detected. All checked records conform to reconciliation rules.</td></tr>"}
        </tbody>
    </table>
    
    <div class="footer">
        Commerce Truth Lab v1.0 &bull; Evidence-First E-Commerce Audit Engine &bull; Founded by <a href="https://syed-muslim-shah-portfolio.vercel.app/" target="_blank">Syed Muslim Shah</a>
    </div>
</body>
</html>"""
        return HTMLResponse(
            content=html_doc,
            headers={"Content-Disposition": f"inline; filename=ctl-audit-{workspace_id}.html"}
        )
