"""initial_production_schema

Revision ID: 87dcf646c5e0
Revises: 
Create Date: 2026-09-21 09:44:18.389827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87dcf646c5e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('audit_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('evaluated_orders', sa.Integer(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('healthy_controls_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_runs_workspace_id'), 'audit_runs', ['workspace_id'], unique=False)
    op.create_table('upload_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('mapped_columns', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_metadata_workspace_id'), 'upload_metadata', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('joined_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.add_column('courier_settlements', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_courier_settlements_workspace_id'), 'courier_settlements', ['workspace_id'], unique=False)
    op.add_column('data_sources', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_data_sources_workspace_id'), 'data_sources', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_findings_workspace_id'), 'findings', ['workspace_id'], unique=False)
    op.add_column('orders', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_workspace_id'), 'orders', ['workspace_id'], unique=False)
    op.add_column('payments', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_workspace_id'), 'payments', ['workspace_id'], unique=False)
    op.add_column('purchase_signals', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_purchase_signals_workspace_id'), 'purchase_signals', ['workspace_id'], unique=False)
    op.add_column('refunds', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_refunds_workspace_id'), 'refunds', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_workspace_id'), table_name='refunds')
    op.drop_column('refunds', 'workspace_id')
    op.drop_index(op.f('ix_purchase_signals_workspace_id'), table_name='purchase_signals')
    op.drop_column('purchase_signals', 'workspace_id')
    op.drop_index(op.f('ix_payments_workspace_id'), table_name='payments')
    op.drop_column('payments', 'workspace_id')
    op.drop_index(op.f('ix_orders_workspace_id'), table_name='orders')
    op.drop_column('orders', 'workspace_id')
    op.drop_index(op.f('ix_findings_workspace_id'), table_name='findings')
    op.drop_index(op.f('ix_data_sources_workspace_id'), table_name='data_sources')
    op.drop_column('data_sources', 'workspace_id')
    op.drop_index(op.f('ix_courier_settlements_workspace_id'), table_name='courier_settlements')
    op.drop_column('courier_settlements', 'workspace_id')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_upload_metadata_workspace_id'), table_name='upload_metadata')
    op.drop_table('upload_metadata')
    op.drop_index(op.f('ix_audit_runs_workspace_id'), table_name='audit_runs')
    op.drop_table('audit_runs')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
